name: 📚 Publish - openSUSE Lessons Doc Website
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: 📥 Checkout Repository
      - name: 🔧 Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
        name: 🐍 Setup Python
      - name: 🕒 Set Cache ID
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
        name: 📦 Restore Cache
      - name: 📦 Install Dependencies
        run: pip install -r requirements.txt
      - name: 🚀 Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
