name: 📚 Generate PDF Develop
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    name: Generate pdf
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main 🛠️
        uses: actions/checkout@v2
      - name: Install requirements 📦
        run: "pip install -r requirements.txt"
      - name: Build PDF 📄
        env:
          ENABLE_PDF_EXPORT: 1
        run: "mkdocs build"
      - name: Publish result 🚀
        uses: actions/upload-artifact@v2
        with:
          name: lesson-plan.pdf
          path: ./site/lesson-develop-plan.pdf
